import Provider from './Provider'
import './globals.css'
import Navbar from './views/navbar/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
        <Navbar />
        {children}
        </Provider>
        </body>
    </html>
  )
}
